In [1]:
import torch

In [39]:
a = torch.randint(1, 10, (2, 3))
b = a.unsqueeze(2)
print (a, "\n \n", b)

tensor([[4, 1, 7],
        [7, 7, 6]]) 
 
 tensor([[[4],
         [1],
         [7]],

        [[7],
         [7],
         [6]]])


In [30]:
c = torch.randint(1, 10, (2, 2))
print(c, "\n \n",  c[..., 0])

tensor([[6, 8],
        [9, 4]]) 
 
 tensor([6, 9])


In [53]:
d = torch.Tensor([1, 7, 3]).unsqueeze(0)
e = torch.Tensor([4, 5, 6]).unsqueeze(0)

f = torch.cat([d, e], dim=0)

_, h = torch.max(f, dim=0)
h


tensor([1, 0, 1])

In [57]:
a = torch.Tensor([7, 2, 3])

In [60]:
print(a[0:1].size())
print(a[0].size())

print(a[0:1])
print(a[0])

torch.Size([1])
torch.Size([])
tensor([7.])
tensor(7.)


In [66]:
a = torch.Tensor([[1, 2], [3, 4]])
b = torch.Tensor([3, 4])

torch.flatten(a)

tensor([1., 2., 3., 4.])

In [78]:
t = torch.Tensor([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(t.size())
t

torch.Size([2, 2, 2])


tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

In [85]:
torch.flatten(t, start_dim=-3, end_dim=-1)

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

In [86]:
a = torch.zeros((2, 2, 10))




tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [2]:
int(1.5)
int(1.9)

1

In [6]:
print(f"dd {4/2}")

dd 2.0


In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F 

m = torch.randn(1, 4, 4)
print(m)

F.max_pool2d(m, 2)

tensor([[[-1.3866, -1.0832, -0.5945,  0.4864],
         [ 0.6523, -1.1140,  1.1232,  0.4016],
         [-1.3505,  0.3469, -1.3115, -0.1783],
         [-0.8589,  0.6176, -0.0857,  0.2903]]])


tensor([[[0.6523, 1.1232],
         [0.6176, 0.2903]]])

In [5]:
for i in range(1, 2):
    print(i)

type(range(2))

1


range